
#ifndef myoptions_h
#define myoptions_h

/* Generated by myoptions.h generator - v0.8.1 */
/* https://e2002.github.io/docs/myoptions-generator.html?r=71,2,5,19,42,43,60,62&i=1,2,3,4,15,16,17,34&v=2,15,-1,255,22,16,4,33 */
/* Put this file next to yoRadio.ino and restart Arduino IDE. */

/* !!! Attention !!! */
/* This configuration depends on some additional libraries. Please install them using the library manager: */
/* Adafruit GFX Library, Adafruit ILI9341, XPT2046_Touchscreen */

/* !!! Do not be alarmed, all right, the default values ​​are not included in this file !!! */

#define DSP_MODEL           DSP_ILI9341
#define DSP_HSPI            true
#define TFT_DC              2
#define TFT_CS              15
#define I2S_DOUT            22
#define I2S_BCLK            16
#define I2S_LRC             4
#define TS_MODEL            TS_MODEL_XPT2046
#define TS_CS               33

// Extra added defines as per https://github.com/e2002/yoradio/wiki/ESP32-TFT-Boards-configurations, ESP32-2432S028R section
#define LED_INVERT          true
#define TFT_RST             -1
#define LED_BUILTIN         17
#define BRIGHTNESS_PIN      21
#define TS_SPIPINS          25, 39, 32    /* SCK, MISO, MOSI */
#define LIGHT_SENSOR        34
#define AUTOBACKLIGHT_MAX   1024

#endif
