#ifndef myoptions_h
#define myoptions_h

/* Generated by myoptions.h generator - v0.8.1 */
/* https://e2002.github.io/docs/myoptions-generator.html?r=71,2,4,7,12,43,54,66,67&i=5,6,15,16,17,28,29,30,40,41&v=21,22,27,26,25,39,36,34,2,0 */
/* Put this file next to yoRadio.ino and restart Arduino IDE. */

/* !!! Attention !!! */
/* This configuration depends on some additional libraries. Please install them using the library manager: */
/* Adafruit GFX Library, Adafruit SSD1306, OneButton, IRremoteESP8266 */

/* !!! Do not be alarmed, all right, the default values ​​are not included in this file !!! */

#define DSP_MODEL			DSP_SSD1306
#define ENC_BTNR			39
#define ENC_BTNL			36
#define ENC_BTNB			34
#define ENC_INTERNALPULLUP			false
#define LED_BUILTIN			2
#define IR_PIN			0


#endif
