#ifndef myoptions_h
#define myoptions_h

/* Generated by myoptions.h generator - v0.8.1 */
/* https://e2002.github.io/docs/myoptions-generator.html?r=71,2,4,12,43,54&i=5,6,15,16,17,28,29,30&v=21,22,27,26,25,35,33,32 */
/* Put this file next to yoRadio.ino and restart Arduino IDE. */

/* !!! Attention !!! */
/* This configuration depends on some additional libraries. Please install them using the library manager: */
/* Adafruit GFX Library, Adafruit SSD1306, OneButton */

/* !!! Do not be alarmed, all right, the default values ​​are not included in this file !!! */

#define DSP_MODEL                   DSP_SSD1306
#define ENC_BTNR                    35
#define ENC_BTNL                    33
#define ENC_BTNB                    32
#define ENC_INTERNALPULLUP          false


#endif
